### PR TITLE
Enabled CORS to better facilitate using bookmarklets cross-origin.

### PR DESCRIPTION
**Pull request by cr0wst**
In order for a bookmarklet to make an AJAX request ex: `$.getJSON('http://localhost:3000/usstates/api/v1/states/abbrev/mi', function(j) { console.log(j) });` CORS must be enabled.

I've added middleware to put headers on the response to allow for this.

### CODE REVIEW

**Review by cr0wst — COMMENTED** [review]
I'm not sure exactly what caused the comments to get removed and then added.  I didn't touch them, but it could be an encoding difference between Atom on MacOS and whatever IDE you used.

**Comment by squireChuck** [comment]
Phew, been a while on this one - I feel like I remember the CORS error at one point (even did a bunch of reading before testing out your fork)... but when I went to reproduce this from my `master`, I found that I could hit the app just fine while running the bookmarklet or dev console script on `http://jacksoncoffeeco.com/`. (Needs to be an `http` site since trying hitting the app from an `https` enabled site results in a [mixed-content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) error.) For the specifics:

Using the Fetch API in the dev console:
```javascript
fetch('http://localhost:3000/usstates/api/v1/states/abbrev/MI', { method:'GET', headers: new Headers() })
.then(function (response) {
    return response.json()
})
.then((data) => {
	console.log(data)
});
```

As a bookmarklet:
```javascript
javascript: (function() {fetch('http://localhost:3000/usstates/api/v1/states/abbrev/MI', { method:'GET', headers: new Headers() }).then(function (response) { return response.json() }).then((data) => {console.log(data)});})()
```

And the results - first the request headers:
```
Request URL:http://localhost:3000/usstates/api/v1/states/abbrev/MI
Request Method:GET
Status Code:304 Not Modified
Remote Address:[::1]:3000
Referrer Policy:no-referrer-when-downgrade
Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Host:localhost:3000
If-None-Match:W/"1a0-UK3aGUUS3iQB8cen1NQ+WWAKGKI"
Origin:http://jacksoncoffeeco.com
Referer:http://jacksoncoffeeco.com/
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
```

The response headers
```
Connection:keep-alive
Date:Fri, 17 Mar 2017 23:16:01 GMT
ETag:W/"1a0-UK3aGUUS3iQB8cen1NQ+WWAKGKI"
X-Powered-By:Express
```
And the response body (containing the expected results):
```json
{
    "name": "Michigan",
    "abbrev": "MI",
    "capital": "Lansing",
    "addresses": [
        {
            "street": "4235 Woodward Ave",
            "city": "Detroit",
            "state": "MI",
            "zip": "48201"
        },
        {
            "street": "423 W Eleven Mile Rd",
            "city": "Royal Oak",
            "state": "MI",
            "zip": "48067"
        },
        {
            "street": "26765 Gratiot Ave",
            "city": "Roseville",
            "state": "MI",
            "zip": "48066"
        }
    ],
    "driversLicenseDescription": [
        "1 char's, 12 num's"
    ],
    "sampleLicense": "A123654456321",
    "unionAdmissionDate": "1837-01-26"
}
```

**Comment by squireChuck** [comment]
So I guess if I can see what the CORS headers fix, I'll get this merged in. But if not, I'll just close the PR - you've already got the solution usable in your fork so I'll pull it from ya if it's needed in the future.

**Comment by cr0wst** [comment]
The CORS headers fix when trying to access using a bookmarklet not pointed to localhost, ie if you were running on another server.

Try this one (your master branch running on port 4002) from that same site with http:
```javascript
fetch('http://smcrow.net:4002/usstates/api/v1/states/abbrev/MI', { method:'GET', headers: new Headers() })
.then(function (response) {
    return response.json()
})
.then((data) => {
	console.log(data)
});
```

my fixed version is running on 4003.  You'll get a CORs issue on 4002 but not 4003.

**Comment by squireChuck** [comment]
Ahh, cool, it checked out for me, so I went ahead and merged it. Thanks for the explanation, demo, and the PR!!

**Pull request merged**
